## CI build for personal R docker image
version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: prestevez/r-pres2
    docker:
      - image: cimg/base:stable
        auth:
            username: $DOCKERHUB_USER
            password: $DOCKERHUB_PWD
jobs:
  build-and-push:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run:
          name: Login to DockerHub
          command: echo "$DOCKERHUB_PWD" | docker login -u "$DOCKERHUB_USER" --password-stdin
      - run:
          name: Build and push using buildx
          command: |
            source VERSION
            TAG=$VMAJOR.$VMINOR.${CIRCLE_SHA1:0:7}
            docker buildx build . \
              -t $IMAGE_NAME:$TAG \
              -t $IMAGE_NAME:latest \
              --push
workflows:
  version: 2
  build-master:
    jobs:
      - build-and-push:
          filters:
            branches:
              only: main
          context:
              - authentication
  weekly:
      triggers:
          - schedule:
              cron: 0 3 * * 1
              filters:
                branches:
                  only: master
      jobs:
        - build-and-push:
            filters:
              branches:
                only: master
            context:
                - authentication
## CRON job should be changed to first check if there are differences, then tagged using a flag for CRON job